### ISSUE TITLE
Could You Share Category Information of the Dataset?

### ISSUE THREAD

**Issue by HeegyuKim** [XMUDM/DQABench#1]
Hello, thank you for publishing excellent work!

I'd like to analyze the DQABench dataset with the category for research purposes, but the published dataset does not include it.

Specifically, Fig 1-(a) and 5-(a) in the paper illustrate a comprehensive analysis of the "Percentage of different Q&A types in online DB communities"  and a radar chart on categories.

Thank you

**Comment by simple-lb** [comment]
Thank you for your attention to our work!

We tried to find the intermediate results of the previous experiment 和 found a test set with category labels. You can download it in 1_Dataset_of_Benchmark_DQA/general_knowledge_with_tags. I hope it will be helpful to you. 

It should be noted that the answer field of this dataset has not been rewritten by LLM. If you need the rewritten answer, please search with the complete dataset of DQA.
